### ISSUE TITLE
Add a Gradle Wrapper

### ISSUE THREAD

**Issue by lingocoder** [lingocoder/jpms.springboot.jersey#1]
Discovered by [*this heads-up*](https://github.com/akud/modular-java-example/issues/1#issuecomment-540759351) from @akud.

**Comment by akud** [comment]
Duplicating my comment from https://github.com/lingocoder/jpms.springboot.jersey/issues/2#issuecomment-544279341 for visibility:

here's my gradle version:

```
~/workspace/jpms.springboot.jersey/authn$ gradle --version

------------------------------------------------------------
Gradle 5.0
------------------------------------------------------------

Build time:   2018-11-26 11:48:43 UTC
Revision:     7fc6e5abf2fc5fe0824aec8a0f5462664dbcd987

Kotlin DSL:   1.0.4
Kotlin:       1.3.10
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.3 (Oracle Corporation 11.0.3+7-Ubuntu-1ubuntu218.10.1)
OS:           Linux 4.18.0-25-generic amd64
```

I'd send you a pr adding a wrapper, but my version doesn't work.

You may find the following useful; I did when I was doing heavy work building modules. It's a function to find the nearest gradle wrapper and execute that. I found it useful because I was often `cd`ing into subprojects to try and check their dependency trees, or build parts of them. Enjoy!

```
function gw() {
  if [ -z "$GW_LEVEL" ]; then
    GW_LEVEL=0
  elif [ $GW_LEVEL -gt 5 ]; then
    echo "Couldn't find gradlew in 5 levels"
    return 1
  fi
  DIR="."
  for ((i = 0; i < GW_LEVEL; i++)); do
    DIR="../$DIR"
  done
  if [ -f "${DIR}/gradlew" ]; then
    ${DIR}/gradlew $*
  else
    GW_LEVEL=$((GW_LEVEL + 1)) gw $*
  fi
}
```

**Comment by lingocoder** [comment]
OK. I've actioned my first new year's resolution by finally uploading the wrapper files. Those wrapper files existed locally all along. But they were unintentionally listed in *`.gitignore`*. So when I first pushed everything else, the wrapper files were excluded.  

Thanks @akud for the script by the way.
